pipeline {
    agent any
    tools {
        gradle 'gradle'
        jdk 'open-jdk-21'
    }
    environment {
        REPOSITORY_URI = "970547378654.dkr.ecr.us-west-1.amazonaws.com/user-service"
        IMAGE_TAG = "dev-${BUILD_NUMBER}"
    }
    stages {
        stage("Clean Workspace"){
            steps {
                sh 'echo cleaning workspace'
                cleanWs()
            }
        }
        stage("Git Checkout") {
            steps {
                sh 'echo cloning git repo'
                git branch: 'master',
                    url: 'https://github.com/balmiki-badatya/user-service.git'
            }
        }
        stage("Gradle Build") {
            steps {
                sh 'echo building gradle project'
                sh './gradlew clean build -x test --refresh-dependencies'
            }
        }
        stage("Unit Test") {
            steps {
                sh './gradlew test'
            }
        }
        stage("Sonarqube Analysis") {
            steps {
                sh 'curl -v https://sonar.microops.io/api/system/status || echo "SonarQube server unreachable"'
                withSonarQubeEnv('sonarqube-server') {
                    sh './gradlew sonar -Dsonar.qualitygate=microops-custom-gate'
                }
            }
        }
        stage("Quality Gate Check") {
            steps {
                timeout(time: 20, unit: 'MINUTES') {
                     waitForQualityGate abortPipeline: false, credentialsId: 'sonar-jenkins-token'
                }
            }
        }
        stage("Trivy file scan") {
            steps {
                sh 'trivy fs --format table --output trivy-scan.txt .'
            }
        }
        stage("OWASP Dependency Check") {
            steps {
                dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'Dependency-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        stage("Docker Tag and Push to ECR") {
            steps {
                sh '''aws ecr get-login-password --region us-west-1 | \
                docker login --username AWS --password-stdin 970547378654.dkr.ecr.us-west-1.amazonaws.com'''
                sh  'echo Successfully logged in to ECR'
                sh 'docker build -t user-service .'
                sh 'docker tag user-service:latest ${REPOSITORY_URI}:${IMAGE_TAG}'
                sh 'docker push  ${REPOSITORY_URI}:${IMAGE_TAG}'
            }
        }

    }
}