pipeline {
    agent any
    tools {
        gradle 'gradle'
        jdk 'open-jdk-21'
    }
    stages {
        stage("Clean Workspace"){
            steps {
                sh 'echo cleaning workspace'
                cleanWs()
            }
        }
        stage("Git Checkout") {
            steps {
                sh 'echo cloning git repo'
                git branch: 'master',
                    url: 'https://github.com/balmiki-badatya/user-service.git'
            }
        }
        stage("Gradle Build") {
            steps {
                sh 'echo building gradle project'
                sh './gradlew clean build -x test --refresh-dependencies'
            }
        }
        stage("Unit Test") {
            steps {
                sh './gradlew test'
            }
        }
        stage("Sonarqube Analysis") {
            steps {
                sh 'curl -v https://sonar.microops.io/api/system/status || echo "SonarQube server unreachable"'
                withSonarQubeEnv('sonarqube-server') {
                    sh './gradlew sonar -Dsonar.qualitygate=microops-custom-gate'
                }
            }
        }
        stage("Quality Gate Check") {
            steps {
                timeout(time: 20, unit: 'MINUTES') {
                     waitForQualityGate abortPipeline: false, credentialsId: 'sonar-jenkins-token'
                }
            }
        }
        stage("Trivy file scan") {
            steps {
                sh 'trivy fs --format table --output trivy-scan.txt .'
            }
        }
        stage("OWASP Dependency Check") {
            steps {
                dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'Dependency-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
    }
}