spring.application.name=user-service
# Use this for WebFlux (replaces server.servlet.context-path)
spring.webflux.base-path=/user-service

# Management endpoints will now be at /course-service/actuator
management.endpoints.web.exposure.include=*
server.port=9090


spring.config.import=aws-secretsmanager:/dev/user-service/db/secrets

logging.level.org.springframework.core.env=DEBUG
logging.level.io.awspring.cloud.secretsmanager=DEBUG

logging.file.name=/app/fs/user-service.log
logging.level.root=debug

# JPA PostgreSQL
spring.datasource.url=jdbc:postgresql://${rds_endpoint}:5432/postgres
spring.datasource.username=${db_username}
spring.datasource.password=${db_cred}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect