name: User Service CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      NAME: BALMIKI Badatya
    name: Build User-Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - run: |
          ls -la
          echo ${{ env.NAME }}
  test:
    name: Unit Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls -la