name: User Service CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build User-Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - run: | 
          ls -la
          echo ${{ secrets.NAME }}
  test:
    name: Unit Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
  env-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: env-test
        run: |
          echo ${{ github.REF_NAME }}
          echo ${{ github.run_number }}
          echo $GITHUB_RUN_NUMBER
  output-generate:
    name: output generator
    id: op-generator
    runs-on: ubuntu-latest
    needs: [ build,test,env-test ]
    steps:
      - name: output
        id: op
        run: |
          echo "age=29" >> $GITHUB_OUTPUT
      - name: output-access-from-step
        run: echo "age is - ${{ steps.op.outputs.age }}"
  output-printer:
    name: output printer
    runs-on: ubuntu-latest
    needs: [ build, env-test, output-generate]
    steps:
      run: |
        echo "age from different job: ${{ jobs.op-generator.steps.op.outputs.age }}"