name: User Service CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build User-Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - run: | 
          ls -la
          echo ${{ secrets.NAME }}
  test:
    name: Unit Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls -la