name: user-service deployment
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          ENV_VAR=${{ github.run_number }}
          echo $ENV_VAR
