name: user-service deployment
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build
        run: |
          ./gradlew clean build test
          ls -lrt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service
          path: .
  build-docker-image:
    name: Build docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: user-service
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: user-service-github-actions-session
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: user-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
  update-image-tag:
    name: Update image tag in values.yaml
    runs-on: ubuntu-latest
    needs: [ build, build-docker-image ]
    steps:
      - name: Checkout app config repo
        uses: actions/checkout@v5
        with:
          repository: balmiki-badatya/skillsync-devops
          path: skillsync-devops
          token: ${{ secrets.REPO_PAT }}
      - name: Update values
        env:
          IMAGE_TAG: ${{ needs.build-docker-image.outputs.IMAGE_TAG }}
        run: |
          ls -lrt
          cd skillsync-devops/helm
          echo 'tag=$IMAGE_TAG'
          yq -i '.image.tag = $IMAGE_TAG' user-service-chart/values.yaml  
          cat user-service-chart/values.yaml
  
